---
title: "Interpretable Analysis of School Policy Decisions, Decision Trees"
author: "Charles Saluski"
# date: "1/4/2022"
output: pdf_document
---

```{r}
library(glmnet)
library(mlr3)
library(mlr3learners)
library(data.table)
library(mlr3extralearners)
library(mlr3tuning)

csv.data.loc <- "./Data Sources CSV"
ic.joined.dt.loc <- paste(csv.data.loc, "/ic.cwis.nces.computed.combined.csv", sep = "")
cwis.joined.dt.loc <- paste(csv.data.loc, "/cwis.nces.computed.combined.csv", sep = "")
cl.joined.dt.loc <- paste(csv.data.loc, "/ic.cwis.nces.cl.computed.combined.csv", sep = "")

ic.joined.dt <- as.data.table(read.csv(ic.joined.dt.loc))
cwis.joined.dt <- as.data.table(read.csv(cwis.joined.dt.loc))
cl.joined.dt <- as.data.table(read.csv(cl.joined.dt.loc))

ic.joined.dt <- ic.joined.dt[complete.cases(ic.joined.dt)]
cwis.joined.dt <- cwis.joined.dt[complete.cases(cwis.joined.dt)]
cl.joined.dt <- cl.joined.dt[complete.cases(cl.joined.dt)]

data.set.list <- list("IC" = ic.joined.dt, "CWIS" = cwis.joined.dt, "CL" = cl.joined.dt)
```

```{r}
# these variables are character and variables used in earlier joins so they are not needed
standard.exclude.cols <- c("X", "State.District.ID", "CWIS_session", "IC_NCES.District.Name..to.check.", "IC_School.District", "IC_Teacher_leader_More_than_6", "IC_Total_more_than_10")
cfa.exclude.cols <- c(standard.exclude.cols, "CWIS_CFA_avg")
cwis.exclude.cols <- c(cfa.exclude.cols, "CWIS_DBDM_avg", "CWIS_PD_avg", "CWIS_Leadership_avg")

exclude.set.list <- list("standard" = standard.exclude.cols, "CFA" = cfa.exclude.cols, "CWIS" = cwis.exclude.cols)


task.list <- list()
for (exclude.set in names(exclude.set.list)) {
  exclude.cols <- exclude.set.list[[exclude.set]]
  for (data.set in names(data.set.list)) {
    curr.dt <- data.set.list[[data.set]][, !c(..exclude.cols)]
    task.name <- paste(data.set, "excl.", exclude.set)
    task.list[[task.name]] <- TaskRegr$new(id = task.name, backend = curr.dt, target = "CWIS_ETLP_avg")
  }
}

for (exclude.set in names(exclude.set.list)) {
  if (exclude.set == "standard") {
    exclude.cols <- exclude.set.list[[exclude.set]]
    for (data.set in names(data.set.list)) {
      curr.dt <- data.set.list[[data.set]][, !c("CWIS_ETLP_avg", ..exclude.cols)]
      task.name <- paste("CFA", data.set, "excl.", exclude.set)
      task.list[[task.name]] <- TaskRegr$new(id = task.name, backend = curr.dt, target = "CWIS_CFA_avg")
    }
  }
}

task.name.vec <- names(task.list)
```

```{r}
set.seed(123)
num.folds <- 10

# uncomment to run code in parallel, has some issues for me, as it allocates
# memory for all of the tasks at once, instead of over time and not all at once.
# if (future::supportsMulticore()) {
#   future::plan("multicore", workers=4)
# } else {
#   future::plan(future::multisession)
# }
# task.backend.names <- c("ic.predict.dt", )

measure <- msr("regr.mse")

resampling <- rsmp("cv", folds = num.folds)
# cv_glmnet returns 2 models, one with s1 and one with minimum
learner.name.vec <- c("regr.cv_glmnet", "regr.featureless", "regr.ctree", "regr.cforest")
learner.list <- list()
for (name in learner.name.vec) {
  learner.list[[name]] <- lrn(name)
}

learner.list[["xgboost.at.lrn"]] <- AutoTuner$new(
  learner = lrn("regr.xgboost"),
  resampling = rsmp("cv", folds = 3),
  measure = measure, # mean squared error
  search_space = ps(
    eta = p_dbl(lower = 0, upper = 1),
    nrounds = p_int(lower = 1, upper = 16)
  ),
  terminator = trm("none"),
  tuner = tnr("grid_search", resolution = 4),
  store_tuning_instance = TRUE
)

learner.name.vec <- names(learner.list)

benchmark.obj <- benchmark_grid(
  task = task.list,
  learners = learner.list,
  resamplings = list(resampling)
  # tasks, learners, and resamplings
  # we'll only give a learner vector, same tasks and resamplings
)

benchmark.res <- benchmark(benchmark.obj, store_models = TRUE)
result.dt <- benchmark.res$score(measure)
```

```{r}
library(ggplot2)
method.levels <- result.dt[, .(mean = mean(regr.mse)), by = learner_id][order(-mean), learner_id]
result.dt[, Method := factor(learner_id, method.levels)]
err.plot <- ggplot() +
  geom_point(data = result.dt, aes(x = regr.mse, y = Method)) +
  facet_grid(task_id ~ .)

if (!dir.exists("./img_out/decision_trees/")) {
  dir.create("./img_out/decision_trees/")
}
png(filename = "./img_out/decision_trees/decision.tree.loss.png", width = 6, height = 20, unit = "in", res = 200)
print(err.plot)
dev.off()
```

```{r}
ctree_var_extract <- function(ctree, var.acc.v) {
  if (!is.null(ctree)) {
    var.acc.v <- c(var.acc.v, attributes(ctree$info$p.value)$names)
    for (i in 1:length(ctree$kids)) {
      var.acc.v <- ctree_var_extract(ctree$kids[[i]], var.acc.v)
    }
  }
  var.acc.v
}

ctree.dt <- result.dt[learner_id == "regr.ctree"]

# convert all the above code into this single block
ctree.var.dt <- ctree.dt[, {
  curr.learner <- learner[[1]]
  res.vars <- ctree_var_extract(curr.learner$model$node, vector())
  as.data.table(table(res.vars))
}, by=.(iteration, task_id)]
ctree.var.dt[, times.in.tree := N]
ctree.var.dt[, occurence.n.folds := sum(times.in.tree != 0), by=.(res.vars, task_id)]
```

```{r}
for (task.name in task.name.vec) {
  var.count.plot <- ggplot() +
      geom_point(data = ctree.var.dt[task_id == task.name], aes(x = times.in.tree, y = res.vars)) +
      facet_grid(occurence.n.folds ~ ., scales = "free", space = "free") 

    dest <- "./img_out/decision_trees/"
    if (!dir.exists(dest)) {
      dir.create(dest)
    }
    filename <- paste(task.name, "count.png", sep = "_")
    filename <- paste0(dest, filename, sep = "")
    png(filename = filename, width = 8, height = 6, unit = "in", res = 200)
    print(var.count.plot)
    dev.off()
}
```


```{r}
ctree.model.list <- list()
if (!dir.exists("./img_out/decision_trees/trees")) {
  dir.create("./img_out/decision_trees/trees")
}
for (task.name in task.name.vec) {
  curr.dt <- ctree.dt[task_id == task.name]
  dest <- paste("./img_out/decision_trees/trees/", task.name, sep = "")
  if (!dir.exists(dest)) {
    dir.create(dest)
  }
  for (fold in 1:num.folds) {
    curr.tree <- curr.dt[iteration == fold]$learner[[1]]$model

    filename <- paste(task.name, fold, "tree.png", sep = "_")
    filename <- paste(dest, filename, sep = "/")
    png(filename = filename, width = 20, height = 6, unit = "in", res = 200)
    plot(curr.tree)
    dev.off()
  }
}
```